// define your tokens

#define TOKEN 1
#define PLUS 2
#define MINUS 3
#define MULTIPLY 4
#define DIVIDE 5
#define ASSIGNMENT 6
#define EQUALITY 7
#define LESSTHAN 8
#define GREATERTHAN 9
#define LESSTHANOREQUALS 10
#define GREATERTHANOREQUALS 11
#define NOTEQUALS 12
#define LEFTB 13
#define RIGHTB 14
#define COLON 15
#define COMMA 16
#define DEF 17
#define ENDDEF 18
#define IF 19
#define ENDIF 20
#define ELSE 21
#define WHILE 22
#define ENDWHILE 23
#define PRINT 24
#define INPUT 25
#define TRUE 26
#define FALSE 27
#define RETURN 28
#define IDENTIFIER 29
#define NUMBER  30
#define STRING 31
#define COMMENT 32